# Generated by Django 3.2.25 on 2024-07-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
