# Generated by Django 3.2.25 on 2025-05-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='settings_dictionary_ads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anon',
            name='settings_post_ads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anon',
            name='settings_space_ads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anon',
            name='settings_word_ads',
            field=models.BooleanField(default=True),
        ),
    ]
