# Generated by Django 3.2.25 on 2025-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_auto_20250517_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='total_through_put',
            field=models.IntegerField(default=0),
        ),
    ]
