# Generated by Django 3.2.25 on 2025-05-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0003_storefront_total_through_put'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storefront',
            unique_together={('author', 'title')},
        ),
    ]
