# Generated by Django 3.2.25 on 2024-08-02 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0004_auto_20240802_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_factor', models.FloatField(default=0.0)),
                ('contact_factor', models.FloatField(default=0.0)),
                ('meet_up_factor', models.FloatField(default=0.0)),
                ('business_factor', models.FloatField(default=0.0)),
                ('sell_to_factor', models.FloatField(default=0.0)),
                ('buy_from_factor', models.FloatField(default=0.0)),
                ('courier_factor', models.FloatField(default=0.0)),
                ('dictionary_factor', models.FloatField(default=0.0)),
                ('space_factor', models.FloatField(default=0.0)),
                ('governance_factor', models.FloatField(default=0.0)),
                ('host_author', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='affinity_host_author', to='Bable.author')),
                ('mutual', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='affinity_mutual', to='Bable.author')),
                ('mutual_friend', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='affinity_mutual_friend', to='Bable.author')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='friends',
            field=models.ManyToManyField(default=None, related_name='friends', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='anon',
            name='product_sort_char',
            field=models.CharField(choices=[('name', 'Name Alphabetical'), ('-name', 'Name Reverse Alphabetical'), ('price', 'Most Expensive'), ('-price', 'Least Expensive'), ('latest_change_date', 'Most Recently Changed'), ('-latest_change_date', 'Least Recently Changed'), ('sum_comments', 'Most Commented'), ('-sum_comments', 'Least Commented'), ('sum_invoices', 'Most Purchased'), ('-sum_invoices', 'Least Purchased'), ('sponsor_count', 'Most Sponsors'), ('-sponsor_count', 'Least Sponsors')], default='views', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='storefront_sort_char',
            field=models.CharField(choices=[('author__username', 'Author Alphabetical'), ('-author__username', 'Author Reverse Alphabetical'), ('logo__the_word_itself', 'Logo Alphabetical'), ('-logo__the_word_itself', 'Logo Reverse Alphabetical'), ('logo__home_dictionary__the_dictionary_itself', 'Logo Home Dic Alpha'), ('-logo__home_dictionary__the_dictionary_itself', 'Logo Home Dic Reverse Alpha'), ('logo__author__username', 'Logo Author Alpha'), ('-logo__author__username', 'Logo Author Reverse Alpha'), ('title', 'Title Alphabetical'), ('-title', 'Title Reverse Alphabetical'), ('products_count', 'Most Products'), ('-products_count', 'Least Products'), ('sales_count', 'Most Sales'), ('-sales_count', 'Least Sales'), ('business_admins_count', 'Most Business Partners'), ('-business_admins_count', 'Least Business Partners')], default='views', max_length=180),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='revoked_authors_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='latest_change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='price',
            name='sponsor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='business_admins_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='products_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anon',
            name='excluded_dic_authors',
            field=models.ManyToManyField(default=None, related_name='excluded_dic_authors', to='Bable.Author'),
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mutual_friends_count', models.IntegerField(default=0)),
                ('host_author', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='host_author', to='Bable.author')),
                ('mutual', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='mutual', to='Bable.author')),
                ('mutual_friends_affinity', models.ManyToManyField(default=None, to='Bable.Affinity')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='mutuals_associate',
            field=models.ManyToManyField(default=None, to='Bable.Associate'),
        ),
    ]
