# Generated by Django 3.2.25 on 2025-05-18 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0004_alter_storefront_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='estimated_arrival_date',
            field=models.DateField(default=datetime.date(2025, 6, 11)),
        ),
        migrations.AddField(
            model_name='courier',
            name='leave_from_date',
            field=models.DateField(default=datetime.date(2025, 5, 18)),
        ),
        migrations.AlterField(
            model_name='courier',
            name='estimated_arrival_time',
            field=models.TimeField(default=(12, 0)),
        ),
        migrations.AlterField(
            model_name='courier',
            name='leave_from_time',
            field=models.TimeField(default=(12, 0)),
        ),
    ]
