# Generated by Django 3.2.25 on 2024-08-02 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0005_auto_20240802_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='latest_change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='storefront',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anon',
            name='product_sort_char',
            field=models.CharField(choices=[('name', 'Name Alphabetical'), ('-name', 'Name Reverse Alphabetical'), ('price', 'Most Expensive'), ('-price', 'Least Expensive'), ('latest_change_date', 'Most Recently Changed'), ('-latest_change_date', 'Least Recently Changed'), ('sum_comments', 'Most Commented'), ('-sum_comments', 'Least Commented'), ('sum_invoices', 'Most Purchased'), ('-sum_invoices', 'Least Purchased'), ('sponsor_count', 'Most Sponsors'), ('-sponsor_count', 'Least Sponsors'), ('views', 'Most Views'), ('-views', 'Least Views')], default='views', max_length=180),
        ),
        migrations.AlterField(
            model_name='anon',
            name='storefront_sort_char',
            field=models.CharField(choices=[('author__username', 'Author Alphabetical'), ('-author__username', 'Author Reverse Alphabetical'), ('logo__the_word_itself', 'Logo Alphabetical'), ('-logo__the_word_itself', 'Logo Reverse Alphabetical'), ('logo__home_dictionary__the_dictionary_itself', 'Logo Home Dic Alpha'), ('-logo__home_dictionary__the_dictionary_itself', 'Logo Home Dic Reverse Alpha'), ('logo__author__username', 'Logo Author Alpha'), ('-logo__author__username', 'Logo Author Reverse Alpha'), ('title', 'Title Alphabetical'), ('-title', 'Title Reverse Alphabetical'), ('products_count', 'Most Products'), ('-products_count', 'Least Products'), ('sales_count', 'Most Sales'), ('-sales_count', 'Least Sales'), ('business_admins_count', 'Most Business Partners'), ('-business_admins_count', 'Least Business Partners'), ('latest_change_date', 'Most Recent Change'), ('-latest_change_date', 'Least Recent Change'), ('views', 'Most Viewed'), ('-views', 'Least Viewed')], default='views', max_length=180),
        ),
    ]
