# Generated by Django 3.2.25 on 2024-08-04 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0006_auto_20240802_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_agent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='requested_agent',
            name='if_loggedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requested_agent',
            name='if_username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='requested_agent',
            name='page',
            field=models.CharField(default='', max_length=200),
        ),
    ]
