# Generated by Django 3.2.25 on 2024-08-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0009_alter_post_max_sponsor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storefront',
            old_name='template_section_size_1_1',
            new_name='template_section_size_disclaimer_height',
        ),
        migrations.RenameField(
            model_name='storefront',
            old_name='template_section_size_1_2',
            new_name='template_section_size_disclaimer_left',
        ),
        migrations.RenameField(
            model_name='storefront',
            old_name='template_section_size_1_3',
            new_name='template_section_size_disclaimer_right',
        ),
        migrations.RenameField(
            model_name='storefront',
            old_name='template_section_size_2_2',
            new_name='template_section_size_preview_height',
        ),
        migrations.RenameField(
            model_name='storefront',
            old_name='template_section_size_2_1',
            new_name='template_section_size_preview_left',
        ),
        migrations.RenameField(
            model_name='storefront',
            old_name='template_section_size_2_3',
            new_name='template_section_size_preview_right',
        ),
        migrations.RenameField(
            model_name='storefront',
            old_name='template_section_size_3_1',
            new_name='template_section_size_title_height',
        ),
        migrations.RenameField(
            model_name='storefront',
            old_name='template_section_size_3_2',
            new_name='template_section_size_title_left',
        ),
        migrations.RenameField(
            model_name='storefront',
            old_name='template_section_size_3_3',
            new_name='template_section_size_title_right',
        ),
    ]
