# Generated by Django 3.2.25 on 2024-08-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0010_auto_20240823_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='template_section_size_disclaimer_height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='template_section_size_preview_height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='template_section_size_title_height',
            field=models.IntegerField(default=100),
        ),
    ]
