# Generated by Django 3.2.25 on 2024-11-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0011_auto_20240829_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='new_notifications',
            field=models.ManyToManyField(default=None, related_name='new_notifications', to='Bable.Notification'),
        ),
        migrations.AddField(
            model_name='userviews',
            name='httpxforwardfor',
            field=models.TextField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='userviews',
            name='ip_address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='anon',
            name='notifications',
            field=models.ManyToManyField(default=None, related_name='old_notifications', to='Bable.Notification'),
        ),
    ]
