# Generated by Django 3.2.25 on 2024-11-28 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0013_auto_20241123_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preferred_pronouns', 'Preferred Pronouns'), ('trigger_adjectives', 'Trigger Adjectives'), ('trigger_nouns', 'Trigger Nouns'), ('trigger_verbs', 'Trigger Verbs'), ('trigger_adverbs', 'Trigger Adverbs'), ('concerned_for_as_targeted_pronouns', 'Concern for as Targeted Pronouns'), ('concerned_for_as_accusational_verbs', 'Concern for as Accusational Verbs'), ('mantras', 'Mantras/Chants'), ('karmas', 'Karmas/Deservations'), ('dharmas', 'Dharmas/Duties'), ('ways', 'Ways/Types')], default='pronoun', max_length=140)),
                ('word', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='anon_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='anon_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='attribute_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='viewcount', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='attribute_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='comment_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='comment_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='dictionary_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='viewcount', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='dictionary_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='example_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='viewcount', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='example_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='viewcount', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='past_votes_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='past_votes_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='post_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='post_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='product_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='product_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='space_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='space_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='sponsor_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='viewcount', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='sponsor_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='viewcount', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='storefront_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='storefront_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='word_sort_depth_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='viewcount', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='word_sort_from_date_char',
            field=models.CharField(choices=[('15,0,0,0,0,0', '15 Minutes'), ('30,0,0,0,0,0', '30 Minutes'), ('45,0,0,0,0,0', '45 Minutes'), ('0,1,0,0,0,0', 'Hourly'), ('0,2,0,0,0,0', '2 Hourly'), ('0,4,0,0,0,0', '4 Hourly'), ('0,6,0,0,0,0', '6 Hourly'), ('0,8,0,0,0,0', '8 Hourly'), ('0,10,0,0,0,0', '10 Hourly'), ('0,12,0,0,0,0', '12 Hourly'), ('0,16,0,0,0,0', '16 Hourly'), ('0,18,0,0,0,0', '18 Hourly'), ('0,20,0,0,0,0', '20 Hourly'), ('0,0,1,0,0,0', '1 Daily'), ('0,36,0,0,0,0', '1.5 Daily'), ('0,0,2,0,0,0', '2 Daily'), ('0,0,3,0,0,0', '3 Daily'), ('0,0,4,0,0,0', '4 Daily'), ('0,0,5,0,0,0', '5 Daily'), ('0,0,0,1,0,0', 'Weekly'), ('0,0,0,2,0,0', '2 Weekly'), ('0,0,0,0,1,0', 'Monthly'), ('0,0,0,0,2,0', '2 Monthly'), ('0,0,0,0,3,0', '3 Monthly'), ('0,0,0,0,4,0', '4 Monthly'), ('0,0,0,0,6,0', '6 Monthly'), ('0,0,0,0,9,0', '9 Monthly'), ('0,0,0,0,0,1', 'Yearly'), ('0,0,0,0,18,0', '18 Monthly'), ('0,0,0,0,0,2', '2 Yearly'), ('0,0,0,0,0,3', '3 Yearly'), ('0,0,0,0,0,4', '4 Yearly'), ('0,0,0,0,0,5', '5 Yearly'), ('0,0,0,0,0,120', 'All Time')], default='', max_length=180),
        ),
        migrations.CreateModel(
            name='BaseTokenSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_who_searched', models.CharField(default='', max_length=140)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('base_token', models.ManyToManyField(default=None, to='Bable.BaseToken')),
                ('usernames_returned', models.ManyToManyField(default=None, to='Bable.Author')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='base_token_searches',
            field=models.ManyToManyField(default=None, to='Bable.BaseTokenSearch'),
        ),
        migrations.AddField(
            model_name='anon',
            name='concerned_for_as_accusational_verbs',
            field=models.ManyToManyField(default=None, related_name='accusational_verbs', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='concerned_for_as_targeted_pronouns',
            field=models.ManyToManyField(default=None, related_name='targeted_pronouns', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='dharmas',
            field=models.ManyToManyField(default=None, related_name='dharmas', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='karmas',
            field=models.ManyToManyField(default=None, related_name='kharmas', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='mantras',
            field=models.ManyToManyField(default=None, related_name='mantras', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='preferred_pronouns',
            field=models.ManyToManyField(default=None, related_name='preferred_pronouns', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='trigger_adjectives',
            field=models.ManyToManyField(default=None, related_name='trigger_adjectives', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='trigger_adverbs',
            field=models.ManyToManyField(default=None, related_name='trigger_adverbs', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='trigger_nouns',
            field=models.ManyToManyField(default=None, related_name='trigger_nouns', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='trigger_verbs',
            field=models.ManyToManyField(default=None, related_name='trigger_verbs', to='Bable.BaseToken'),
        ),
        migrations.AddField(
            model_name='anon',
            name='ways',
            field=models.ManyToManyField(default=None, related_name='ways', to='Bable.BaseToken'),
        ),
    ]
