# Generated by Django 3.2.25 on 2024-11-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0014_auto_20241128_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anon',
            old_name='sum_earnt_from_supports',
            new_name='sum_earnt_from_sponsors',
        ),
        migrations.RenameField(
            model_name='anon',
            old_name='sum_supported_by_sponsors',
            new_name='sum_sponsors',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='sponsor_count',
            new_name='sum_sponsors',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='sponsor_count',
            new_name='sum_earnt_from_sponsors',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='sponsor_count',
            new_name='sum_earnt_from_sponsors',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='sponsor_count',
            new_name='sum_earnt_from_sponsors',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='sponsor_count',
            new_name='sum_earnt_from_sponsors',
        ),
        migrations.RenameField(
            model_name='userspecificjavascriptvariableviewlearning',
            old_name='sponsor_allowable_expenditure',
            new_name='sum_earnt_from_sponsors',
        ),
        migrations.RenameField(
            model_name='userspecificjavascriptvariableviewlearning',
            old_name='sponsor_count',
            new_name='sum_sponsor_allowable_expenditure',
        ),
        migrations.RenameField(
            model_name='userspecificjavascriptvariableviewlearning',
            old_name='sum_sponsor_earnings',
            new_name='sum_sponsors',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='sponsor',
            new_name='sponsors',
        ),
        migrations.AddField(
            model_name='angelnumber',
            name='sum_earnt_from_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='angelnumber',
            name='sum_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barcode',
            name='sum_earnt_from_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='sum_earnt_from_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='sum_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='definition',
            name='sum_earnt_from_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='sum_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sum_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='sum_earnt_from_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='sum_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchurl',
            name='sum_earnt_from_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='sum_sponsors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_angelnumber',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_anon',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_barcode',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_comment',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_definition',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_dictionary',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_job',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_jobapp',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_post',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_price',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_searchurl',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_space',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_viewvariable',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_on_word',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='votings',
            name='sum_earnt_from_sponsors',
            field=models.IntegerField(default=0),
        ),
    ]
