# Generated by Django 3.2.25 on 2024-11-30 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0020_auto_20241128_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviews',
            name='anon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bable.anon'),
        ),
    ]
