# Generated by Django 3.2.4 on 2024-12-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0021_alter_userviews_anon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviews',
            name='httpxforwardfor',
            field=models.TextField(default='', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='userviews',
            name='ip_address',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userviews',
            name='page_view',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userviews',
            name='previous_page',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userviews',
            name='previous_view_id',
            field=models.CharField(default='', max_length=144, null=True),
        ),
    ]
