# Generated by Django 3.2.4 on 2024-12-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0022_auto_20241206_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angelnumber',
            name='description',
            field=models.TextField(max_length=1440),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='', max_length=1440),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='', max_length=1440),
        ),
    ]
